pipeline{
    agent any
    stages{
        stage("intro"){
            sh "hello every one,this is my first pipeline"
        }
    } 
        stage("system daetils"){
            steps{
                uname
            }
        }
        stage("memory deatils"){
            steps{
               lscpu 
            }    
        }

    }
}
