pipeline {
    agent any

    stages {
        stage("Intro") {
            steps {
                sh 'echo "Hello everyone, this is my first pipeline"'
            }
        }

        stage("System Details") {
            steps {
                sh "uname -a"
            }
        }

        stage("Memory Details") {
            steps {
                sh "lscpu"
            }
        }
    }
}
